name: pokemon_tcg_battle
description: A new Flutter project to display Pokémon cards and compare HP.
publish_to: 'none' # Remove this line if you plan to publish the package.

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
